import type { InsertTool } from "@workspace/db";

export type SeedTool = Omit<InsertTool, "embedding">;

/**
 * Real Headout internal tools, sourced from a GitHub-org audit (headout/* repos,
 * ~300 scanned) plus the HeadoutAgentsConfig registry (bundles.json + per-skill
 * SKILL.md frontmatter). Unlike lib/seedData.ts (fictional demo/eval fixtures —
 * left untouched; catalogueQuality.test.ts pins retrieval-quality regressions
 * against those exact names), every row here maps to a real repo or a real,
 * currently-installable Claude Code skill.
 *
 * `ownerName`/`ownerSlackId` are deliberately blank: this audit only had repo
 * metadata, not a roster of who owns what, and inventing owners would be
 * actively misleading. Rows are unclaimed (claimed: false) until a real owner
 * claims them via the manage-token flow. `team` is a best-effort functional
 * guess from repo context, not verified org data — expect to correct some.
 *
 * Scope: filtered out of the ~300 repos — core product microservices
 * (zapdos, wall-street, athena, uruk, minerva, magellan, muse, rosetta, ...),
 * pure infra-as-code (terraform-modules, helm-charts, chokidar, arsenal, ...),
 * scaffolding/service templates (python-fastapi-template, spring-boot-service-
 * template — that's the separate scaffolding-taxonomy workstream), and repos
 * with a blank description and no README (too little signal to describe
 * honestly). Real Zeps *agents* are intentionally not fabricated here — only
 * the Zeps platform itself is listed; the individual zep rows in the fictional
 * seed remain the only zep-type examples until a live Zeps sync exists.
 */
export const REAL_SEED_TOOLS: SeedTool[] = [
  // ── MCP servers (agent-callable) ──────────────────────────────────────
  {
    type: "mcp",
    title: "Delphi",
    oneLiner: "Codebase-intelligence Slack bot and MCP — ask it about any Headout repo.",
    description:
      "An intelligent Slack bot and MCP server for engineering teams: contextual code analysis, documentation retrieval and technical Q&A over Headout's codebases. Uses a LangGraph state-machine to classify queries and route them to code analysis, internal docs (RAG), Slack workspace search, or web search, with thread-aware follow-ups. Pre-scope which repo you're asking about — huge queries can take ~15min.",
    tags: ["mcp", "codebase-intelligence", "rag", "slack-bot", "delphi"],
    ownerName: "",
    ownerSlackId: "",
    team: "Applied AI",
    url: "https://github.com/headout/delphi",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "mcp",
    title: "Argus MCP",
    oneLiner: "Ask an AI agent about live Argus incidents — read-only.",
    description:
      "MCP server exposing Argus incident-investigation tools to Claude Desktop/Code and other MCP clients: list/filter incidents, pull full context for one (source URLs, alert routing, service/team), and ask which services alerted this week. Read-only — no ack/resolve/silence; use the Argus dashboard for those.",
    tags: ["mcp", "incidents", "on-call", "argus", "monitoring"],
    ownerName: "",
    ownerSlackId: "",
    team: "Platform",
    url: "https://github.com/headout/argus-mcp",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "app",
    title: "Argus",
    oneLiner: "Unified alerting, metrics and on-call platform for Headout Engineering.",
    description:
      "The underlying alerting/metrics/on-call platform behind Argus MCP: incident tracking, alert routing to the right on-call rotation, and a dashboard for acking/resolving/silencing. Go backend + web dashboard, deployed on EKS.",
    tags: ["alerting", "on-call", "incidents", "monitoring", "dashboard"],
    ownerName: "",
    ownerSlackId: "",
    team: "Platform",
    url: "https://github.com/headout/argus",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "mcp",
    title: "Oak",
    oneLiner: "MCP server for the Eevee design system — tokens, components, icons.",
    description:
      "Gives AI assistants (Cursor, Claude Code) programmatic access to Headout's Eevee design system: design tokens, text styles, component docs/props/usage, the Onix icon library, and development rules. Cached, with Prometheus metrics.",
    tags: ["mcp", "design-system", "eevee", "tokens", "components"],
    ownerName: "",
    ownerSlackId: "",
    team: "Design Systems",
    url: "https://github.com/headout/oak",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "mcp",
    title: "Headout MCP Server",
    oneLiner: "MCP giving AI agents access to Headout's experiences and itinerary data.",
    description:
      "A Model Context Protocol server exposing the Headout API for discovering experiences, tours and POIs, retrieving reviews/pricing/availability, and building day-by-day itineraries — for AI agents doing travel planning.",
    tags: ["mcp", "experiences", "itinerary", "travel", "catalog"],
    ownerName: "",
    ownerSlackId: "",
    team: "Applied AI",
    url: "https://github.com/headout/headout-mcp-server",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "mcp",
    title: "Aviator",
    oneLiner: "MCP server for Compass — Headout's tour-content RAG system.",
    description:
      "Query tour content, configuration and reviews through Headout's Compass RAG pipeline via MCP tools (semantic content search, policy/feature lookups). Inventory/pricing tools are on the roadmap.",
    tags: ["mcp", "rag", "compass", "tour-content", "search"],
    ownerName: "",
    ownerSlackId: "",
    team: "Applied AI",
    url: "https://github.com/headout/aviator",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "mcp",
    title: "Porygon MCP",
    oneLiner: "Product-knowledge MCP — flows, design-system components, specs, journeys.",
    description:
      "The Product OS knowledge backend: stores flows, design-system components, specs, journeys and product philosophy, retrievable with an intent-aware engine (fetch_asset, understand, navigate, why, discover, lookup) over Postgres + pgvector. Lets Cursor/Claude Code answer product questions without digging through Notion or source.",
    tags: ["mcp", "product-os", "knowledge-base", "porygon"],
    ownerName: "",
    ownerSlackId: "",
    team: "Product",
    url: "https://github.com/headout/porygon-mcp",
    source: "seed",
    status: "live",
    accessLevel: "request",
    visibility: "org",
  },
  {
    type: "mcp",
    title: "TalentMCP",
    oneLiner: "Ask an AI agent about Headout's people, teams, culture and open roles.",
    description:
      "MCP backend with two hard-separated surfaces: an external one for job seekers (anonymized aggregates, k=3 suppression, playbook, open roles) and an internal one for Headouters (named lookup, role history, claim-your-profile). Internal access requires LinkedIn sign-in plus a one-time @headout.com email code on every tool call.",
    tags: ["mcp", "people", "culture", "hiring", "internal"],
    ownerName: "",
    ownerSlackId: "",
    team: "People",
    url: "https://github.com/headout/talentmcp",
    source: "seed",
    status: "live",
    accessLevel: "request",
    visibility: "org",
  },
  {
    type: "mcp",
    title: "Headout MCP Servers (Suppliers, etc.)",
    oneLiner: "Collection repo for Headout-internal MCP servers.",
    description:
      "A repo housing internally-facing MCP servers (e.g. a suppliers MCP server) that expose internal data/actions to AI agents. Grouped by language (Python) with per-server entrypoints.",
    tags: ["mcp", "internal", "collection", "suppliers"],
    ownerName: "",
    ownerSlackId: "",
    team: "Applied AI",
    url: "https://github.com/headout/mcp-servers",
    source: "seed",
    status: "live",
    accessLevel: "request",
    visibility: "org",
  },

  // ── Bots (Slack / GitHub) ──────────────────────────────────────────────
  {
    type: "app",
    title: "Vulcan (VulcanHO)",
    oneLiner: "AI-powered GitHub App that reviews every PR automatically.",
    description:
      "Reviews every PR: enqueues webhook events into a Postgres job queue, runs Semgrep + OSV dependency scanning and domain classification in parallel, builds context from prior learnings, and sends a Claude Code SDK session (with call-graph MCP tools for impact-aware analysis) against the actual repo. Classifies post-merge whether its suggestions were adopted, and feeds that back into future reviews. Comments only — no merge-gating API (v1); that's the tracked v2.",
    tags: ["pr-review", "ai", "github-app", "security-scanning", "vulcan"],
    ownerName: "",
    ownerSlackId: "",
    team: "Applied AI",
    url: "https://github.com/headout/reviewbot",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "app",
    title: "Plato",
    oneLiner: "Autonomous coding agent — mention it in Slack to fix a bug or ship a small feature.",
    description:
      "Fixes bugs, builds small features, answers codebase questions and opens PRs, all triggered from Slack. Built on the Claude Agent SDK + Temporal workflows + Kubernetes: an orchestrator classifies intent, a Temporal workflow spins up a repo-agent pod, and a GitHub App then watches the resulting PR — auto-investigating and pushing fixes if CI fails or reviewers request changes (up to 3 retries). Incremental changes on existing repos only, ~30% merge rate — not a greenfield builder.",
    tags: ["autonomous-coding", "slack-bot", "pr-automation", "plato"],
    ownerName: "",
    ownerSlackId: "",
    team: "Applied AI",
    url: "https://github.com/headout/PlatoBot",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "slack-bot",
    title: "Wanda (barbar)",
    oneLiner: "Oncall debugging agent that triages bug reports posted to Slack.",
    description:
      "Classifies an incoming Slack bug report to the owning team (POD), picks a debugging runbook, executes investigative tools (log search, SQL queries, ticket lookup) and posts findings back to the thread. Every reply carries 👍/👎 feedback buttons; a 👎 also fires a negative-feedback alert so oncall sees bad replies without digging.",
    tags: ["slack-bot", "oncall", "debugging", "triage", "agent"],
    ownerName: "",
    ownerSlackId: "",
    team: "Platform",
    url: "https://github.com/headout/barbar",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "slack-bot",
    title: "Bar",
    oneLiner: "Slack app that manages the engineering workflow between Slack and Jira.",
    description:
      "A Bolt-for-JavaScript Slack app handling the back-and-forth between Slack and Jira for bug/engineering workflows. Pairs with Bar UI (the bug-stats dashboard).",
    tags: ["slack-bot", "jira", "bugs", "workflow"],
    ownerName: "",
    ownerSlackId: "",
    team: "QA",
    url: "https://github.com/headout/bar",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "app",
    title: "Bar UI — JIRA Bug Stats Dashboard",
    oneLiner: "Visualizes JIRA bug stats — TAT scoring, trends, severity breakdowns.",
    description:
      "Next.js dashboard for bug tracking: automatic TAT (turn-around-time) risk scoring by severity and time elapsed, daily bug trend and severity-distribution charts, team/date filtering, and the ability to update JIRA issue status and comments directly from the dashboard.",
    tags: ["dashboard", "jira", "bugs", "analytics", "qa"],
    ownerName: "",
    ownerSlackId: "",
    team: "QA",
    url: "https://github.com/headout/bar-ui",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "slack-bot",
    title: "PR Pulse",
    oneLiner: "Pod-aware PR digest, Slack Home tab, and stale-PR nudges.",
    description:
      "A long-running Express server posting a scheduled per-pod Slack digest (stale / changes-requested / awaiting-review / approved), a personal App Home tab, and event DMs (review requested with size/time estimate, changes requested, approved, merged, merge conflicts). Only claims \"ready to merge\" when nothing visibly blocks it. Stale nudges with opt-in warn-then-close.",
    tags: ["slack-bot", "pull-requests", "digest", "engineering-productivity"],
    ownerName: "",
    ownerSlackId: "",
    team: "Platform",
    url: "https://github.com/headout/pr-pulse",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "slack-bot",
    title: "Iris",
    oneLiner: "Weekly frontend UI/UX digest for PMs and designers, posted to Slack.",
    description:
      "A weekly digest of frontend/UI changes across zapdos, next-deimos, espeon, eevee, kirby and hub-frontend, written for PMs and designers (not engineers) and posted to Slack via GitHub Actions on a metered Claude Sonnet 5 key.",
    tags: ["slack-bot", "digest", "frontend", "pm", "design"],
    ownerName: "",
    ownerSlackId: "",
    team: "Frontend",
    url: "https://github.com/headout/iris",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },

  // ── QA / testing ────────────────────────────────────────────────────
  {
    type: "app",
    title: "Zenith",
    oneLiner: "Multi-agent QA \"master brain\" — failure triage, locator self-heal, PR-aware test runs.",
    description:
      "Sits between CI, GitHub, Slack and dev bots across 30+ services. Ingests Cucumber failures and diagnoses root cause with auto-heal for broken locators (opens one combined fix PR); risk-scores a PR to pick impacted test suites and can write new test scenarios; and auto-routes a dev PR to the right QA repos, spins ODEs, generates and runs tests, and reports back — no human in the loop. Reachable via Slack slash command, @mention, HTTP, or MCP.",
    tags: ["qa", "test-automation", "ci", "self-healing", "multi-agent"],
    ownerName: "",
    ownerSlackId: "",
    team: "QA",
    url: "https://github.com/headout/zenith",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "script",
    title: "Alakazam",
    oneLiner: "AI agent that visually regression-tests a build against a baseline or a spec.",
    description:
      "Takes a natural-language prompt describing what to check, captures screenshots via a real headless browser, and returns a pass/fail verdict with diffs and findings. Two modes: Regression (compare a build URL against a baseline) and Validate (check a single build URL against a prompt + pass criteria, no baseline needed). Built on the Claude Agent SDK + Bun.",
    tags: ["qa", "visual-regression", "ai-agent", "testing"],
    ownerName: "",
    ownerSlackId: "",
    team: "QA",
    url: "https://github.com/headout/alakazam",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "script",
    title: "Artemis",
    oneLiner: "Write a browser test once, run it on Selenium, Playwright, or DrissionPage.",
    description:
      "A unified framework for browser automation tests: switch the underlying engine (Selenium, Playwright, DrissionPage) with a single configuration value instead of rewriting tests per tool.",
    tags: ["qa", "browser-automation", "selenium", "playwright", "framework"],
    ownerName: "",
    ownerSlackId: "",
    team: "QA",
    url: "https://github.com/headout/artemis",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "script",
    title: "Aura",
    oneLiner: "AI-assisted unified regression automation framework.",
    description:
      "A regression-automation framework that uses AI to help generate and maintain test coverage across Headout services.",
    tags: ["qa", "regression", "automation", "ai"],
    ownerName: "",
    ownerSlackId: "",
    team: "QA",
    url: "https://github.com/headout/aura",
    source: "seed",
    status: "beta",
    accessLevel: "open",
    visibility: "org",
  },

  // ── Product / Product OS ────────────────────────────────────────────
  {
    type: "skill",
    title: "Product OS",
    oneLiner: "End-to-end product agent — PM + data + designer in one Claude Code workflow.",
    description:
      "Install as a Claude Code plugin and run /product-os to go from problem to direction to execution options to HTML prototypes (with a design-critique loop) to optional live-page injection, backed by Porygon. Phases: brainstorm (grounded in Slack/Granola/BigQuery/Porygon KB), ideate (2-4 execution options), prototype (Tailwind HTML + screenshots + critique until \"ship\"), and on-demand PRD generation.",
    tags: ["skill", "claude-code", "product", "prototyping", "product-os"],
    ownerName: "",
    ownerSlackId: "",
    team: "Product",
    url: "https://github.com/headout/product-os",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "app",
    title: "Porygon Dashboard",
    oneLiner: "Admin dashboard for the Porygon product-knowledge MCP.",
    description:
      "Next.js dashboard for browsing and administering the Porygon MCP's knowledge base (flows, specs, components, journeys). BFF proxy pattern keeps porygon API keys off the browser.",
    tags: ["dashboard", "product-os", "porygon", "admin"],
    ownerName: "",
    ownerSlackId: "",
    team: "Product",
    url: "https://github.com/headout/porygon-dashboard",
    source: "seed",
    status: "live",
    accessLevel: "request",
    visibility: "org",
  },
  {
    type: "skill",
    title: "Headout PM OS",
    oneLiner: "9 specialist PM skills covering the full product cycle, as a Claude plugin.",
    description:
      "A Claude Code / Cowork plugin marketplace for the Headout product team: pm-orchestrator (routes to the right specialist), problem-framer, idea-generator, data-analyst (behavioral questions + BigQuery), and more, bundled with the team's durable context (org structure, pod scopes, glossary, project history).",
    tags: ["skill", "product", "pm", "plugin", "claude-code"],
    ownerName: "",
    ownerSlackId: "",
    team: "Product",
    url: "https://github.com/headout/pm-os-marketplace",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },

  // ── Design systems ───────────────────────────────────────────────────
  {
    type: "docs",
    title: "Eevee",
    oneLiner: "Headout's design system — components, tokens, and Storybook.",
    description:
      "The design system consumed across Headout's frontends via Panda CSS — referenced by the Oak MCP (tokens/components/icons), the create-component and migrate-to-pandacss skills, and the design-system adoption tracker.",
    tags: ["design-system", "eevee", "components", "tokens", "panda-css"],
    ownerName: "",
    ownerSlackId: "",
    team: "Design Systems",
    url: "https://github.com/headout/eevee",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "plugin",
    title: "Eevee Tokens Visualizer",
    oneLiner: "VS Code extension to visualize Eevee design tokens inline.",
    description:
      "A VS Code extension that surfaces Eevee design-system tokens (colors, spacing, typography) directly in the editor while writing frontend code.",
    tags: ["vscode-extension", "design-system", "eevee", "tokens"],
    ownerName: "",
    ownerSlackId: "",
    team: "Design Systems",
    url: "https://github.com/headout/eevee-tokens-visualizer",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "script",
    title: "Design System Adoption Tracker",
    oneLiner: "AI-powered static analysis: which custom components can migrate to Eevee?",
    description:
      "Extracts React components, styled-components and Panda CSS recipes from a codebase via AST parsing, then uses an LLM (GPT-4o-mini or local Ollama) to compare them against Eevee design-system components and generate migration reports with confidence scores. Pre-filtering cuts LLM calls by 99%+.",
    tags: ["design-system", "migration", "static-analysis", "ai", "eevee"],
    ownerName: "",
    ownerSlackId: "",
    team: "Design Systems",
    url: "https://github.com/headout/design-system-adoption-tracker",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },

  // ── Growth / GTM / Product plugins (Claude skills) ──────────────────
  {
    type: "skill",
    title: "Weekly Growth Review",
    oneLiner: "Weekly revenue growth analysis with seasonality-adjusted, CE-level root-cause analysis.",
    description:
      "A Claude plugin (Cowork + Claude Code) that produces L1/L2/L3 weekly revenue growth analysis with seasonality-adjusted root-cause breakdowns at the category-experience level.",
    tags: ["skill", "growth", "analytics", "rca", "claude-plugin"],
    ownerName: "",
    ownerSlackId: "",
    team: "Growth",
    url: "https://github.com/headout/knowledge-work-plugins",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "Headout GTM Skills",
    oneLiner: "Claude plugin for GTM: pre-call research briefs and meeting follow-ups.",
    description:
      "POC-scope Claude plugin for the GTM team: a setup check (verifies Granola/Calendar/Gmail connections), meeting-follow-up (recap email + CRM note from a Granola transcript), and pre-call-brief (company/person/history research ahead of an external meeting).",
    tags: ["skill", "gtm", "sales", "meetings", "claude-plugin"],
    ownerName: "",
    ownerSlackId: "",
    team: "GTM",
    url: "https://github.com/headout/headout-gtm-skills",
    source: "seed",
    status: "beta",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "Clarity Session Analysis",
    oneLiner: "Claude skill that turns Microsoft Clarity session recordings into structured insights.",
    description:
      "Given a research brief (pages, product IDs, recording count), pulls Mixpanel funnel context, filters Clarity sessions, watches recordings via a Chrome MCP in agent mode, and compiles per-session observations plus synthesized insights and action items into a new Google Sheet.",
    tags: ["skill", "clarity", "session-analysis", "growth", "product"],
    ownerName: "",
    ownerSlackId: "",
    team: "Growth",
    url: "https://github.com/headout/User-session-analysis-skill",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },

  // ── People / HR ──────────────────────────────────────────────────────
  {
    type: "app",
    title: "Feedback 360",
    oneLiner: "Headout's bi-annual 360° peer feedback and performance review platform.",
    description:
      "Nomination-based 360° feedback covering the full cycle: peer nominations, manager approval, four-directional feedback collection (peer/upward/downward/self), manager 1-1 capture, AI-assisted synthesis, and a structured PIP/performance-action workflow. End-to-end encryption on sensitive content; serves ~700 employees across employee/HR-admin/admin roles.",
    tags: ["hr", "performance-review", "feedback", "people"],
    ownerName: "",
    ownerSlackId: "",
    team: "People",
    url: "https://github.com/headout/feedback-360",
    source: "seed",
    status: "live",
    accessLevel: "request",
    visibility: "org",
  },

  // ── Ops / Finance ────────────────────────────────────────────────────
  {
    type: "app",
    title: "Procurement Tool",
    oneLiner: "Headout's procurement automation UI.",
    description:
      "A Next.js frontend over the prepurchase Django backend for procurement workflows, with a BFF proxy so browser code never sees backend credentials.",
    tags: ["procurement", "finance", "operations", "internal-tool"],
    ownerName: "",
    ownerSlackId: "",
    team: "Finance",
    url: "https://github.com/headout/procurement-tool",
    source: "seed",
    status: "live",
    accessLevel: "request",
    visibility: "org",
  },
  {
    type: "app",
    title: "LAS (Listing Automation Service)",
    oneLiner: "Bulk media automation and listing classification for supply/content teams.",
    description:
      "A FastAPI service with two jobs: bulk media automation (async per-image Kafka pipeline that edits and links images to an entity, with a polling status API) and listing classification (city/subcategory/collection, BigQuery-backed).",
    tags: ["supply", "media-automation", "listing", "classification"],
    ownerName: "",
    ownerSlackId: "",
    team: "Supply",
    url: "https://github.com/headout/las",
    source: "seed",
    status: "live",
    accessLevel: "request",
    visibility: "org",
  },

  // ── Content / Marketing ──────────────────────────────────────────────
  {
    type: "app",
    title: "DAM (Digital Asset Management)",
    oneLiner: "Digital asset management tool for Headout's content teams.",
    description:
      "A Next.js + Panda CSS app for managing and organizing digital assets (images/media) used across Headout's content and marketing surfaces.",
    tags: ["dam", "content", "asset-management"],
    ownerName: "",
    ownerSlackId: "",
    team: "Content",
    url: "https://github.com/headout/dam",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "app",
    title: "Headout Email Builder",
    oneLiner: "AI-assisted generator for B2C and B2B (Hub) marketing emails.",
    description:
      "Internal tool that uses GPT-4o (server-side, key never exposed to the browser) to generate marketing email content for both consumer and Headout Hub (B2B) audiences.",
    tags: ["email", "marketing", "ai", "content-generation"],
    ownerName: "",
    ownerSlackId: "",
    team: "Growth",
    url: "https://github.com/headout/Email-builder-tool",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "app",
    title: "City Card Generator",
    oneLiner: "Builds printable comparison cards for city tourism attraction passes.",
    description:
      "A web tool that visualizes the savings value proposition of a city pass — individual attraction ticket prices vs. the bundled card price — with up to 24 attractions, tiered/multi-currency pricing, DOCX import, custom branding, and PDF/JPEG export.",
    tags: ["content-generation", "growth", "partnerships", "design-tool"],
    ownerName: "",
    ownerSlackId: "",
    team: "Growth",
    url: "https://github.com/headout/city-card-tool",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "app",
    title: "Headout Popup Platform",
    oneLiner: "Self-hosted popup/modal system for Headout's 400+ domains.",
    description:
      "Built on open-source Formbricks with a thin Cloudflare Worker bridge, deployed via Google Tag Manager, piping email capture into Iterable. Replaces commercial popup SaaS (Sleeknote, Optinmonster, Sumo) that gets cost-prohibitive at Headout's domain count.",
    tags: ["marketing", "popups", "lead-capture", "self-hosted"],
    ownerName: "",
    ownerSlackId: "",
    team: "Growth",
    url: "https://github.com/headout/popup-platform",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "plugin",
    title: "Payload Finder",
    oneLiner: "Browser extension for content managers working in Payload CMS and Prismic.",
    description:
      "Extracts and displays product-card data (category/subcategory/collection IDs) across card layouts, shows page metadata/templates/domain relationships, tracks word counts, and flags migrated pages to prevent accidental edits. Works across Payload, Prismic, Kirby and Headout frameworks.",
    tags: ["browser-extension", "cms", "content", "payload", "prismic"],
    ownerName: "",
    ownerSlackId: "",
    team: "Content",
    url: "https://github.com/headout/payload-finder",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },

  // ── Data / Analytics ─────────────────────────────────────────────────
  {
    type: "app",
    title: "Omni Analytics",
    oneLiner: "Headout's BI/analytics application (headout.omniapp.co).",
    description:
      "The internal deployment of Headout's Omni-based analytics and BI application, used for exploring and visualizing business metrics.",
    tags: ["analytics", "bi", "data", "dashboard"],
    ownerName: "",
    ownerSlackId: "",
    team: "Data",
    url: "https://github.com/headout/omni-analytics",
    source: "seed",
    status: "live",
    accessLevel: "request",
    visibility: "org",
  },
  {
    type: "app",
    title: "RCA Engine (Booking Analytics Hub)",
    oneLiner: "Root-cause analytics for booking metrics.",
    description:
      "An internal analytics app for root-cause analysis on booking metrics — surfacing what moved a number and why.",
    tags: ["analytics", "rca", "bookings", "data"],
    ownerName: "",
    ownerSlackId: "",
    team: "Data",
    url: "https://github.com/headout/rca-engine",
    source: "seed",
    status: "beta",
    accessLevel: "request",
    visibility: "org",
  },
  {
    type: "app",
    title: "Pulse",
    oneLiner: "Pricing recommendation engine for supply partners.",
    description:
      "An internal engine that generates pricing recommendations for supply partners.",
    tags: ["pricing", "supply", "recommendations", "analytics"],
    ownerName: "",
    ownerSlackId: "",
    team: "Supply",
    url: "https://github.com/headout/pulse",
    source: "seed",
    status: "beta",
    accessLevel: "request",
    visibility: "org",
  },

  // ── Engineering productivity / Platform ─────────────────────────────
  {
    type: "app",
    title: "Cope Meter",
    oneLiner: "A Headout-flavored Claude Code activity dashboard — XP, streaks, share cards.",
    description:
      "Reads your local ~/.claude/ files (nothing leaves your machine) to compute a gamified activity snapshot: XP, current/longest streak, a 26-week heatmap, hourly activity, and a Spotify-Wrapped-style downloadable share card. Honest about what's measured vs. estimated (e.g. token/cost coverage depends on what the session JSONL recorded).",
    tags: ["developer-tools", "claude-code", "dashboard", "fun"],
    ownerName: "",
    ownerSlackId: "",
    team: "Engineering",
    url: "https://github.com/headout/cope-meter",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "script",
    title: "YAPT (Yet Another Platform Tool)",
    oneLiner: "One-tap CLI from the platform team: VPN, ECR creds, k8s, Kafka, local env setup.",
    description:
      "A local CLI covering VPN management (incl. an internet-issue fixer), ECR credential refresh, Kubernetes management, Kafka management, one-shot local environment setup for Headout repos, and a supply-chain scanner. Docker-based, macOS-first.",
    tags: ["cli", "platform", "developer-tools", "kubernetes", "vpn"],
    ownerName: "",
    ownerSlackId: "",
    team: "Platform",
    url: "https://github.com/headout/YAPT",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "docs",
    title: "The Headout API Collection (call-me-maybe)",
    oneLiner: "Bruno API collection covering Headout's internal services.",
    description:
      "A version-controlled, folder-based Bruno API collection (like Postman, but git-friendly) — one folder per service, each with request collections. The reference for calling Headout's internal APIs during development.",
    tags: ["docs", "api-reference", "bruno", "internal-apis"],
    ownerName: "",
    ownerSlackId: "",
    team: "Platform",
    url: "https://github.com/headout/call-me-maybe",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "docs",
    title: "HVP Postman Collection",
    oneLiner: "Postman collection of HVP (high-value partner) APIs.",
    description:
      "A maintained Postman collection covering Headout's HVP API surface, for partner-integration development and debugging.",
    tags: ["docs", "api-reference", "postman", "partners"],
    ownerName: "",
    ownerSlackId: "",
    team: "Platform",
    url: "https://github.com/headout/hvp-postman",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "docs",
    title: "Guardian",
    oneLiner: "Headout's SSO standard — the internal central auth service.",
    description:
      "The central authentication service every Headout app integrates with for SSO. Not raw Google OAuth — a dedicated internal service. Pair with the Guardian App Starter Kit when scaffolding a new app.",
    tags: ["auth", "sso", "guardian", "platform", "security"],
    ownerName: "",
    ownerSlackId: "",
    team: "Platform",
    url: "https://github.com/headout/guardian",
    source: "seed",
    status: "live",
    accessLevel: "request",
    visibility: "org",
  },
  {
    type: "docs",
    title: "Guardian App Starter Kit",
    oneLiner: "Starting point for building a new app with Guardian (SSO) integration baked in.",
    description:
      "A reference app scaffold demonstrating a working Guardian auth integration — the fastest way to bootstrap a new internal app with Headout SSO already wired up.",
    tags: ["auth", "sso", "guardian", "starter-kit", "template"],
    ownerName: "",
    ownerSlackId: "",
    team: "Platform",
    url: "https://github.com/headout/Guardian-App-Starter-Kit",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "docs",
    title: "Headout Engineering Onboarding (Odyssey)",
    oneLiner: "Internal documentation site for onboarding Headout engineering teams.",
    description:
      "A docs site (mkdocs-material) behind Guardian auth, covering onboarding material for different Headout engineering teams.",
    tags: ["docs", "onboarding", "engineering"],
    ownerName: "",
    ownerSlackId: "",
    team: "Platform",
    url: "https://github.com/headout/odyssey",
    source: "seed",
    status: "live",
    accessLevel: "request",
    visibility: "org",
  },
  {
    type: "docs",
    title: "eslint-config-headout",
    oneLiner: "Headout's shared, extensible ESLint config.",
    description:
      "Publishes Headout's .eslintrc as an extensible shared package so every JS/TS repo lints against the same standard instead of reinventing it.",
    tags: ["docs", "eslint", "standards", "developer-tools"],
    ownerName: "",
    ownerSlackId: "",
    team: "Platform",
    url: "https://github.com/headout/eslint-config-headout",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },

  // ── Platform meta ────────────────────────────────────────────────────
  {
    type: "app",
    title: "Zeps",
    oneLiner: "Headout's no-code agent platform — workflow automations with connectors and triggers.",
    description:
      "The no-code, agent-based platform for building lightweight workflow automations (connectors + triggers, no custom UI). Storefront's default recommendation for workflow-shaped asks, and it deeplinks into this builder. Individual deployed Zep agents are not listed here yet — that requires a live sync with the Zeps runtime, which doesn't exist yet.",
    tags: ["no-code", "automation", "workflow", "zeps"],
    ownerName: "",
    ownerSlackId: "",
    team: "Applied AI",
    url: "https://github.com/headout/Zeps",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "docs",
    title: "HeadoutAgentsConfig",
    oneLiner: "The org-level config repo for Claude Code / coding-agent skills, rules, and MCP access.",
    description:
      "Common configuration across coding agents (Claude Code, Cursor, Windsurf, Factory, opencode, ...): skills, agent rules, hooks, and .mcp.json. Bundles (common/frontend/backend/meta/misc) curate which skills land on top of always-installed base infra. The single source of truth for which skills/MCPs a Headout engineer has installed — this catalogue's skill rows below are sourced from its bundles.json and per-skill SKILL.md frontmatter.",
    tags: ["docs", "config", "claude-code", "skills", "mcp"],
    ownerName: "",
    ownerSlackId: "",
    team: "Platform",
    url: "https://github.com/headout/HeadoutAgentsConfig",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "app",
    title: "Sauron",
    oneLiner: "Experimental central router binding queries to the right agents and tools.",
    description:
      "Work-in-progress: a central router meant to dynamically connect queries to the right context providers, prompts, tools and agents. Its own README flags it as very much experimental — not yet a dependable production router.",
    tags: ["router", "agents", "experimental", "orchestration"],
    ownerName: "",
    ownerSlackId: "",
    team: "Applied AI",
    url: "https://github.com/headout/Sauron",
    source: "seed",
    status: "beta",
    accessLevel: "request",
    visibility: "org",
  },
];

const HAC_SKILL_BASE_URL =
  "https://github.com/headout/HeadoutAgentsConfig/tree/main/.claude/skills";

/**
 * Real Claude Code skills installed org-wide via HeadoutAgentsConfig, sourced
 * from bundles.json (which skill belongs to which bundle) and each skill's own
 * SKILL.md frontmatter `description` (trimmed/lightly reworded for catalogue
 * display, not paraphrased in meaning). The 7 repo-meta migration/sync skills
 * (claude-to-*-migration-ho, sync-all-agents-ho) are deliberately excluded —
 * bundles.json's own `peerExclude` note says they "operate ON configs / only
 * make sense in the source repo," i.e. not something an engineer invokes.
 */
export const HEADOUT_AGENT_SKILLS: SeedTool[] = [
  // ── common bundle: core for every engineer ──────────────────────────
  {
    type: "skill",
    title: "commit",
    oneLiner: "Stages and creates git commits with a clean conventional message.",
    description:
      "Stages and creates git commits with a clean conventional message and no AI attribution, asking for approval first. Use when the user says \"commit\", \"git commit\", or \"commit and push\".",
    tags: ["skill", "claude-code", "git", "commit", "engineering"],
    ownerName: "",
    ownerSlackId: "",
    team: "Engineering",
    url: `${HAC_SKILL_BASE_URL}/commit-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "create-pr",
    oneLiner: "Pushes the current branch and opens a GitHub PR with a structured summary.",
    description:
      "Pushes the current branch and opens a GitHub pull request with a structured summary and test plan. Use when the user wants to create, open, or submit a PR, or says \"ready for review\".",
    tags: ["skill", "claude-code", "pull-requests", "github", "engineering"],
    ownerName: "",
    ownerSlackId: "",
    team: "Engineering",
    url: `${HAC_SKILL_BASE_URL}/create-pr-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "pr-describe",
    oneLiner: "Generates a PR title and description from the branch diff.",
    description:
      "Generates a PR title and description optimized for human reviewers from the branch diff, without creating the PR. Use when the user wants to write or update a PR description/title.",
    tags: ["skill", "claude-code", "pull-requests", "engineering"],
    ownerName: "",
    ownerSlackId: "",
    team: "Engineering",
    url: `${HAC_SKILL_BASE_URL}/pr-describe-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "resolve-pr-comments",
    oneLiner: "Resolves open PR review comments by making the requested changes.",
    description:
      "Resolves open PR review comments by making the requested code changes and replying in the same review thread. Use when the user wants to address or fix PR/review comments.",
    tags: ["skill", "claude-code", "pull-requests", "code-review", "engineering"],
    ownerName: "",
    ownerSlackId: "",
    team: "Engineering",
    url: `${HAC_SKILL_BASE_URL}/resolve-pr-comments-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "harden-pr",
    oneLiner: "Hardens an open PR through repeated review-and-fix cycles before merge.",
    description:
      "Hardens an open pull request through repeated review-and-fix cycles, surfacing edge cases, error handling and safety gaps and applying fixes before merge. Use for a large or risky PR.",
    tags: ["skill", "claude-code", "pull-requests", "code-review", "engineering"],
    ownerName: "",
    ownerSlackId: "",
    team: "Engineering",
    url: `${HAC_SKILL_BASE_URL}/harden-pr-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "find-skills",
    oneLiner: "Discovers and installs available agent skills matching what you're trying to do.",
    description:
      "Discovers and installs available agent skills that match what the user is trying to do. Use when the user asks \"find a skill for X\" or \"what skills are available\".",
    tags: ["skill", "claude-code", "discovery", "meta", "engineering"],
    ownerName: "",
    ownerSlackId: "",
    team: "Engineering",
    url: `${HAC_SKILL_BASE_URL}/find-skills-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "debug",
    oneLiner: "Debugs a failing issue via logs, database state, and git history.",
    description:
      "Debugs a failing issue via logs, database state, and git history to pinpoint the cause and a fix. Use for a failing test or thrown error — not for production incidents (use investigate).",
    tags: ["skill", "claude-code", "debugging", "engineering"],
    ownerName: "",
    ownerSlackId: "",
    team: "Engineering",
    url: `${HAC_SKILL_BASE_URL}/debug-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "research-agent",
    oneLiner: "Gathers external docs, best practices, and library/API usage.",
    description:
      "Research agent that gathers external documentation, best practices, and library/API usage and reports back findings. Use to research how something works or look up library docs.",
    tags: ["skill", "claude-code", "research", "documentation", "engineering"],
    ownerName: "",
    ownerSlackId: "",
    team: "Engineering",
    url: `${HAC_SKILL_BASE_URL}/research-agent-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "create-plan",
    oneLiner: "Produces a detailed, validated implementation plan through codebase research.",
    description:
      "Produces a detailed, validated implementation plan in thoughts/shared/plans/ through codebase research and iteration. Use when the user asks \"how should we implement\" or \"design the approach\".",
    tags: ["skill", "claude-code", "planning", "engineering"],
    ownerName: "",
    ownerSlackId: "",
    team: "Engineering",
    url: `${HAC_SKILL_BASE_URL}/create-plan-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "implement-plan",
    oneLiner: "Executes an existing plan phase by phase, verifying each step with tests.",
    description:
      "Executes an existing plan from thoughts/shared/plans phase by phase, making code changes and verifying each step with tests. Use when the user says \"implement/execute the plan\".",
    tags: ["skill", "claude-code", "implementation", "planning", "engineering"],
    ownerName: "",
    ownerSlackId: "",
    team: "Engineering",
    url: `${HAC_SKILL_BASE_URL}/implement-plan-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "implement-task",
    oneLiner: "Executes a single scoped implementation task end to end.",
    description:
      "Implementation agent that executes a single scoped task end to end and writes a handoff document when it completes. Typically a sub-step of implement-plan.",
    tags: ["skill", "claude-code", "implementation", "engineering"],
    ownerName: "",
    ownerSlackId: "",
    team: "Engineering",
    url: `${HAC_SKILL_BASE_URL}/implement-task-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "create-jira-tickets",
    oneLiner: "Creates a Jira Epic/Stories/Sub-tasks hierarchy from a plan or spec.",
    description:
      "Creates a Jira hierarchy of Epic, Stories, and Sub-tasks from a feature spec or implementation plan via the Atlassian MCP. Use when the user wants to turn a plan into tickets.",
    tags: ["skill", "claude-code", "jira", "planning", "engineering"],
    ownerName: "",
    ownerSlackId: "",
    team: "Engineering",
    url: `${HAC_SKILL_BASE_URL}/create-jira-tickets-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "club-prs",
    oneLiner: "Merges several GitHub PRs into one combined branch.",
    description:
      "Merges several GitHub PRs into one combined branch, resolving conflicts and producing a single integrated branch. Use to club/combine multiple PRs together.",
    tags: ["skill", "claude-code", "pull-requests", "engineering"],
    ownerName: "",
    ownerSlackId: "",
    team: "Engineering",
    url: `${HAC_SKILL_BASE_URL}/club-prs-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "jira-workflow",
    oneLiner: "Creates a Jira ticket and matching git branch from a task description.",
    description:
      "Creates a Jira ticket and a matching git branch from a task description, or picks up an existing ticket. Use when referencing a ticket ID or saying \"start working on\".",
    tags: ["skill", "claude-code", "jira", "git", "engineering"],
    ownerName: "",
    ownerSlackId: "",
    team: "Engineering",
    url: `${HAC_SKILL_BASE_URL}/jira-workflow-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "update-pr-stack",
    oneLiner: "Updates every PR description in a stacked PR tree with a dependency graph.",
    description:
      "Updates the descriptions of every PR in a stacked PR tree, adding a dependency visualization showing how the PRs build on each other.",
    tags: ["skill", "claude-code", "pull-requests", "engineering"],
    ownerName: "",
    ownerSlackId: "",
    team: "Engineering",
    url: `${HAC_SKILL_BASE_URL}/update-pr-stack-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "resume-handoff",
    oneLiner: "Resumes work from an existing handoff document.",
    description:
      "Resumes work from an existing handoff document, re-reading its state, validating against the current codebase, and continuing where the prior session stopped.",
    tags: ["skill", "claude-code", "continuity", "engineering"],
    ownerName: "",
    ownerSlackId: "",
    team: "Engineering",
    url: `${HAC_SKILL_BASE_URL}/resume-handoff-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "create-handoff",
    oneLiner: "Writes a handoff document capturing current state and next steps.",
    description:
      "Writes a handoff document capturing current state, decisions, and next steps so work can be picked up in a fresh session or by another person.",
    tags: ["skill", "claude-code", "continuity", "engineering"],
    ownerName: "",
    ownerSlackId: "",
    team: "Engineering",
    url: `${HAC_SKILL_BASE_URL}/create-handoff-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "continuity-ledger",
    oneLiner: "Captures goal, decisions, and phase state so work survives a /clear.",
    description:
      "Creates or updates a continuity ledger in thoughts/ledgers/ capturing goal, decisions, and phase state so work survives a /clear or compaction.",
    tags: ["skill", "claude-code", "continuity", "engineering"],
    ownerName: "",
    ownerSlackId: "",
    team: "Engineering",
    url: `${HAC_SKILL_BASE_URL}/continuity-ledger-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },

  // ── frontend bundle ──────────────────────────────────────────────────
  {
    type: "skill",
    title: "frontend-design",
    oneLiner: "Creates distinctive, production-grade frontend interfaces.",
    description:
      "Creates distinctive, production-grade frontend interfaces with polished code that avoids generic AI aesthetics. Use to build or style web components, pages, or dashboards.",
    tags: ["skill", "claude-code", "frontend", "design"],
    ownerName: "",
    ownerSlackId: "",
    team: "Frontend",
    url: `${HAC_SKILL_BASE_URL}/frontend-design-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "create-component",
    oneLiner: "Builds a production-ready Eevee design-system component from a Figma design.",
    description:
      "Builds a production-ready Eevee design system component from a Figma design using Panda CSS, design tokens, and Storybook stories.",
    tags: ["skill", "claude-code", "frontend", "eevee", "design-system"],
    ownerName: "",
    ownerSlackId: "",
    team: "Frontend",
    url: `${HAC_SKILL_BASE_URL}/create-component-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "create-ui-iterations",
    oneLiner: "Produces frontend UI iterations using Eevee's Iteration component.",
    description:
      "Produces frontend iterations with @headout/eevee's Iteration component on a Headout page or component, after confirming the right consumer repo.",
    tags: ["skill", "claude-code", "frontend", "eevee", "design"],
    ownerName: "",
    ownerSlackId: "",
    team: "Frontend",
    url: `${HAC_SKILL_BASE_URL}/create-ui-iterations-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "migrate-to-pandacss",
    oneLiner: "Migrates a component (recursively) from styled-components to Panda CSS/Eevee.",
    description:
      "Migrates a component and its sub-components recursively from legacy styled-components to Panda CSS (@headout/pixie), Eevee atoms, and Onix icons.",
    tags: ["skill", "claude-code", "frontend", "panda-css", "eevee", "migration"],
    ownerName: "",
    ownerSlackId: "",
    team: "Frontend",
    url: `${HAC_SKILL_BASE_URL}/migrate-to-pandacss-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "swift-code-fixer",
    oneLiner: "Fixes common AI-generated Swift/SwiftUI anti-patterns.",
    description:
      "Fixes common AI-generated Swift/SwiftUI anti-patterns in Swift code, SwiftUI views, and SwiftData models. Use when writing or reviewing .swift files or iOS app code.",
    tags: ["skill", "claude-code", "swift", "ios", "mobile"],
    ownerName: "",
    ownerSlackId: "",
    team: "Mobile",
    url: `${HAC_SKILL_BASE_URL}/swift-code-fixer-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },

  // ── backend bundle ───────────────────────────────────────────────────
  {
    type: "skill",
    title: "cache-ops",
    oneLiner: "Maps an entity to all 5 cache layers and generates invalidation commands.",
    description:
      "Maps a Headout entity to all 5 cache layers (CDN, in-memory pods, Redis, DB/cron) and generates bottom-up invalidation commands with blast-radius assessment. Use for \"clear/invalidate/flush cache\".",
    tags: ["skill", "claude-code", "cache", "redis", "cdn", "backend"],
    ownerName: "",
    ownerSlackId: "",
    team: "Backend",
    url: `${HAC_SKILL_BASE_URL}/cache-ops-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "investigate",
    oneLiner: "Root-cause analysis on a live production incident, correlating logs/traces/metrics.",
    description:
      "Performs root-cause analysis on a live production incident across Headout services, correlating logs, traces, metrics, and recent changes. Use for an outage, error spike, latency regression, or an Argus alert.",
    tags: ["skill", "claude-code", "incidents", "on-call", "backend", "argus"],
    ownerName: "",
    ownerSlackId: "",
    team: "Backend",
    url: `${HAC_SKILL_BASE_URL}/investigate-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "mirrord-test",
    oneLiner: "Runs a service locally against a Kubernetes ODE environment via mirrord.",
    description:
      "Runs a service locally with mirrord connected to a Kubernetes ODE environment, handling config, app startup, and end-to-end API testing.",
    tags: ["skill", "claude-code", "mirrord", "ode", "testing", "backend"],
    ownerName: "",
    ownerSlackId: "",
    team: "Backend",
    url: `${HAC_SKILL_BASE_URL}/mirrord-test-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "vendor-booking-browser-automation",
    oneLiner: "Onboards a new vendor booking automation end to end.",
    description:
      "Onboards a new vendor booking automation end to end — collects config, captures page HTML via a bookmarklet, generates locators/data/inventory/booking files, validates XPaths, and registers routing. macOS only.",
    tags: ["skill", "claude-code", "vendor", "automation", "supply"],
    ownerName: "",
    ownerSlackId: "",
    team: "Supply",
    url: `${HAC_SKILL_BASE_URL}/vendor-booking-browser-automation-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },

  // ── meta bundle: agent & skill authoring ─────────────────────────────
  {
    type: "skill",
    title: "create-agents-md",
    oneLiner: "Generates AGENTS.md/CLAUDE.md and rules by exploring a repo's conventions.",
    description:
      "Generates AGENTS.md, CLAUDE.md, and .claude/rules/ files for a repository by exploring the codebase to identify its tech stack, patterns, and conventions.",
    tags: ["skill", "claude-code", "onboarding", "meta", "documentation"],
    ownerName: "",
    ownerSlackId: "",
    team: "Platform",
    url: `${HAC_SKILL_BASE_URL}/create-agents-md-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "skill-developer",
    oneLiner: "Meta-skill for authoring and managing Claude Code skills.",
    description:
      "Meta-skill for authoring and managing Claude Code skills — scaffolds SKILL.md, frontmatter, and skill-rules.json triggers.",
    tags: ["skill", "claude-code", "meta", "skill-authoring"],
    ownerName: "",
    ownerSlackId: "",
    team: "Platform",
    url: `${HAC_SKILL_BASE_URL}/skill-developer-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "add-agent-config",
    oneLiner: "Scaffolds config for porting Claude setups to a new AI coding agent tool.",
    description:
      "Scaffolds the config directory and conversion mapping for a new AI coding agent tool (rules, skills, agent stubs) so existing Claude configs can be ported to it — e.g. adding support for Cursor, Windsurf, Cline, or Aider.",
    tags: ["skill", "claude-code", "meta", "agent-config"],
    ownerName: "",
    ownerSlackId: "",
    team: "Platform",
    url: `${HAC_SKILL_BASE_URL}/add-agent-config-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },

  // ── misc bundle: opt-in extras ────────────────────────────────────────
  {
    type: "skill",
    title: "feature-interview",
    oneLiner: "Interviews the user to produce a comprehensive feature specification.",
    description:
      "Interviews the user with structured questions to produce a comprehensive feature specification. Use when the user asks for a feature spec from scratch.",
    tags: ["skill", "claude-code", "product", "spec", "planning"],
    ownerName: "",
    ownerSlackId: "",
    team: "Product",
    url: `${HAC_SKILL_BASE_URL}/feature-interview-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "multi-repo-plan",
    oneLiner: "Creates coordinated implementation plans spanning multiple repos.",
    description:
      "Creates coordinated implementation plans spanning multiple repos (frontend, backend, infra), passing API/data contracts between them. Use for a cross-repo change.",
    tags: ["skill", "claude-code", "planning", "multi-repo"],
    ownerName: "",
    ownerSlackId: "",
    team: "Engineering",
    url: `${HAC_SKILL_BASE_URL}/multi-repo-plan-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "grafana-monitoring",
    oneLiner: "Suggests Prometheus metrics for a PR and generates Grafana dashboard panels/alerts.",
    description:
      "Analyzes a PR or diff to suggest Prometheus metrics, then generates Grafana dashboard panels and alert rules in the chokidar repo.",
    tags: ["skill", "claude-code", "monitoring", "grafana", "prometheus", "platform"],
    ownerName: "",
    ownerSlackId: "",
    team: "Platform",
    url: `${HAC_SKILL_BASE_URL}/grafana-monitoring-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "deploy-non-prod",
    oneLiner: "Deploys a Headout service to a non-production test or ODE environment.",
    description:
      "Deploys a Headout service to a non-production test or ODE environment, handling build and deploy. Use for \"deploy to test/ode\" or \"deploy bifrost\".",
    tags: ["skill", "claude-code", "deployment", "ode", "platform"],
    ownerName: "",
    ownerSlackId: "",
    team: "Platform",
    url: `${HAC_SKILL_BASE_URL}/deploy-non-prod-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "qa",
    oneLiner: "Claude Code skill for Headout's QA framework workflows.",
    description:
      "An opt-in skill covering Headout's QA framework workflows (bundled under HeadoutAgentsConfig's \"misc\" extras alongside feature-interview, Grafana, and GTM).",
    tags: ["skill", "claude-code", "qa", "testing"],
    ownerName: "",
    ownerSlackId: "",
    team: "QA",
    url: `${HAC_SKILL_BASE_URL}/qa-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "gtm-launch",
    oneLiner: "Generates a complete B2B SaaS go-to-market launch pack from a spec or PR.",
    description:
      "Generates a complete B2B SaaS go-to-market launch pack — launch email, Slack announcement, in-app banner, product tour, and help article — from a repo spec doc, implementation plan, or PR summary.",
    tags: ["skill", "claude-code", "gtm", "launch", "growth"],
    ownerName: "",
    ownerSlackId: "",
    team: "GTM",
    url: `${HAC_SKILL_BASE_URL}/gtm-launch-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },

  // ── standalone skills (present in the repo but not yet in a bundle) ──
  {
    type: "skill",
    title: "kafka-spring-boot",
    oneLiner: "Standardized Kafka setup for Headout Spring Boot (Kotlin) services on AWS MSK.",
    description:
      "Covers adding Kafka to a service, writing/reviewing @KafkaListener / KafkaTemplate producers, configuring consumers to avoid rebalancing (max.poll.records=1, ack-mode=RECORD, auto-commit=false), @RetryableTopic/DLT, Avro + Schema Registry, async processing (sbctxprop/threadpool), and EmbeddedKafka tests. Covers broker endpoints and topic naming (project.event-name).",
    tags: ["skill", "claude-code", "kafka", "spring-boot", "backend", "msk"],
    ownerName: "",
    ownerSlackId: "",
    team: "Backend",
    url: `${HAC_SKILL_BASE_URL}/kafka-spring-boot-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "log-volume-audit",
    oneLiner: "Audits a service's production log volume and opens a PR to demote the noisiest lines.",
    description:
      "Audits a service's production log volume in Coralogix, ranks the top contributing log lines, and opens a PR to demote the noisiest ones to DEBUG (or remove them). Triggers on \"log volume\", \"noisy logs\", or \"logging cost\".",
    tags: ["skill", "claude-code", "logging", "coralogix", "cost", "platform"],
    ownerName: "",
    ownerSlackId: "",
    team: "Platform",
    url: `${HAC_SKILL_BASE_URL}/log-volume-audit-ho`,
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
];

/** Everything: audited GitHub-org tools plus the HeadoutAgentsConfig skill registry. */
export const ALL_REAL_SEED_TOOLS: SeedTool[] = [
  ...REAL_SEED_TOOLS,
  ...HEADOUT_AGENT_SKILLS,
];
