import type { InsertTool } from "@workspace/db";

export type SeedTool = Omit<InsertTool, "embedding">;

/**
 * ~25 realistic, mixed-type internal tools for Headout (a travel/experiences
 * marketplace). `zep`-type rows carry source "zeps-sync" to emulate the Zeps
 * feed; everything else is source "seed".
 */
export const SEED_TOOLS: SeedTool[] = [
  {
    type: "app",
    title: "Inventory Pulse",
    oneLiner:
      "Dashboard for real-time availability and sell-out risk across experiences.",
    description:
      "A web app that aggregates live availability, capacity and pacing for every bookable experience, flags sell-out and undersell risk, and lets supply managers rebalance allocations before slots go stale.",
    tags: ["inventory", "availability", "dashboard", "supply", "forecasting"],
    ownerName: "Priya Nair",
    ownerSlackId: "@priya",
    team: "Supply Ops",
    url: "https://internal.headout.com/inventory-pulse",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "app",
    title: "Review Radar",
    oneLiner: "Sentiment and theme tracker across guest reviews and CSAT.",
    description:
      "Pulls reviews from every channel, clusters them into themes, tracks sentiment over time per experience and city, and surfaces emerging complaints so ops can act before ratings drop.",
    tags: ["reviews", "sentiment", "nlp", "csat", "quality"],
    ownerName: "Diego Alvarez",
    ownerSlackId: "@diego",
    team: "Content",
    url: "https://internal.headout.com/review-radar",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "app",
    title: "Promo Planner",
    oneLiner: "Plan, simulate and schedule discount campaigns by market.",
    description:
      "Growth uses this to model the margin impact of promotions, schedule them per city and channel, and watch redemption in near real time with automatic guardrails on discount depth.",
    tags: ["promotions", "pricing", "growth", "campaigns", "margin"],
    ownerName: "Sara Kim",
    ownerSlackId: "@sara",
    team: "Growth",
    url: "https://internal.headout.com/promo-planner",
    source: "seed",
    status: "beta",
    accessLevel: "request",
    visibility: "org",
  },
  {
    type: "skill",
    title: "Itinerary Writer",
    oneLiner:
      "Claude skill that drafts day-by-day itineraries from a city and trip length.",
    description:
      "A reusable Claude skill that turns a destination, trip duration and traveler preferences into a structured, bookable day-by-day itinerary referencing Headout experiences.",
    tags: ["itinerary", "content", "claude-skill", "copywriting", "travel"],
    ownerName: "Maya Rao",
    ownerSlackId: "@maya",
    team: "Content",
    url: "https://internal.headout.com/skills/itinerary-writer",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "SEO Brief Builder",
    oneLiner: "Generates SEO content briefs for experience landing pages.",
    description:
      "Given a target keyword and city, produces a content brief with search intent, headings, entities to cover and internal links, tuned for Headout's experience pages.",
    tags: ["seo", "content", "marketing", "keywords", "claude-skill"],
    ownerName: "Tom Becker",
    ownerSlackId: "@tom",
    team: "Growth",
    url: "https://internal.headout.com/skills/seo-brief",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "Refund Triage",
    oneLiner: "Classifies refund requests and recommends a resolution path.",
    description:
      "A skill that reads a customer refund request plus booking context and classifies it by policy, fraud risk and urgency, then recommends approve / partial / escalate with a rationale.",
    tags: ["refunds", "support", "policy", "classification", "cx"],
    ownerName: "Lena Fischer",
    ownerSlackId: "@lena",
    team: "Applied AI",
    url: "https://internal.headout.com/skills/refund-triage",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "docs",
    title: "Pricing Playbook",
    oneLiner: "The canonical guide to how dynamic pricing works at Headout.",
    description:
      "Living documentation covering the pricing model, demand signals, guardrails, markdown rules and who owns what, with worked examples for new analysts.",
    tags: ["pricing", "documentation", "playbook", "revenue", "onboarding"],
    ownerName: "Arjun Mehta",
    ownerSlackId: "@arjun",
    team: "Platform",
    url: "https://docs.headout.com/pricing-playbook",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "docs",
    title: "Connector Catalog",
    oneLiner: "Reference for every internal API and data connector available.",
    description:
      "Documents each internal service and data source — auth, rate limits, schemas and example calls — so builders know what already exists before integrating.",
    tags: ["api", "connectors", "reference", "data", "integration"],
    ownerName: "Wei Chen",
    ownerSlackId: "@wei",
    team: "Platform",
    url: "https://docs.headout.com/connectors",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "docs",
    title: "Brand Voice Guide",
    oneLiner: "How Headout writes — tone, do's and don'ts, with examples.",
    description:
      "The editorial standard for all customer-facing copy: voice, tone by context, formatting rules and approved/forbidden phrasings, with before/after examples.",
    tags: ["brand", "voice", "copywriting", "content", "style-guide"],
    ownerName: "Maya Rao",
    ownerSlackId: "@maya",
    team: "Content",
    url: "https://docs.headout.com/brand-voice",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "mcp",
    title: "Bookings MCP",
    oneLiner: "MCP server exposing read-only booking and order lookups.",
    description:
      "A Model Context Protocol server that lets assistants query bookings, orders and fulfillment status by id, email or experience, with org-scoped, read-only access.",
    tags: ["mcp", "bookings", "orders", "lookup", "read-only"],
    ownerName: "Wei Chen",
    ownerSlackId: "@wei",
    team: "Platform",
    url: "https://internal.headout.com/mcp/bookings",
    source: "seed",
    status: "live",
    accessLevel: "request",
    visibility: "org",
  },
  {
    type: "mcp",
    title: "Catalog MCP",
    oneLiner: "MCP for searching the experiences catalog and metadata.",
    description:
      "Exposes semantic and structured search over the full experiences catalog — descriptions, categories, cities, price bands — for use inside AI agents and copilots.",
    tags: ["mcp", "catalog", "search", "experiences", "metadata"],
    ownerName: "Lena Fischer",
    ownerSlackId: "@lena",
    team: "Applied AI",
    url: "https://internal.headout.com/mcp/catalog",
    source: "seed",
    status: "beta",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "plugin",
    title: "Slack Booking Lookup",
    oneLiner: "Slack plugin to fetch booking details with a slash command.",
    description:
      "A Slack plugin that resolves /booking <id> into a rich card with traveler, experience, status and refund eligibility, so support doesn't leave Slack.",
    tags: ["slack", "bookings", "support", "plugin", "lookup"],
    ownerName: "Diego Alvarez",
    ownerSlackId: "@diego",
    team: "Supply Ops",
    url: "https://internal.headout.com/plugins/slack-booking",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "plugin",
    title: "Figma Locale Swapper",
    oneLiner: "Figma plugin that swaps copy into any supported locale.",
    description:
      "Designers run this to preview a frame in any of Headout's supported languages using approved translations, catching layout breakage before handoff.",
    tags: ["figma", "localization", "design", "i18n", "plugin"],
    ownerName: "Sara Kim",
    ownerSlackId: "@sara",
    team: "Content",
    url: "https://internal.headout.com/plugins/figma-locale",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "script",
    title: "Bulk Image Optimizer",
    oneLiner: "CLI script to compress and reformat experience photos at scale.",
    description:
      "A command-line script that batch-resizes, compresses and converts experience imagery to web formats with sane defaults, used before large content imports.",
    tags: ["images", "optimization", "cli", "content", "automation"],
    ownerName: "Tom Becker",
    ownerSlackId: "@tom",
    team: "Content",
    url: "https://github.com/headout/bulk-image-optimizer",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "script",
    title: "Cohort Exporter",
    oneLiner: "Script to export customer cohorts to CSV for analysis.",
    description:
      "Parameterized script that builds customer cohorts from booking behavior and exports them to CSV or the warehouse for growth and retention analysis.",
    tags: ["analytics", "cohorts", "export", "growth", "csv"],
    ownerName: "Sara Kim",
    ownerSlackId: "@sara",
    team: "Growth",
    url: "https://github.com/headout/cohort-exporter",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "script",
    title: "Schema Diff Bot",
    oneLiner: "Script that diffs warehouse schemas and posts changes.",
    description:
      "Runs on a schedule to detect added, dropped or changed columns across warehouse tables and posts a readable diff so downstream owners aren't surprised.",
    tags: ["data", "warehouse", "schema", "automation", "monitoring"],
    ownerName: "Wei Chen",
    ownerSlackId: "@wei",
    team: "Platform",
    url: "https://github.com/headout/schema-diff-bot",
    source: "seed",
    status: "beta",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "slack-bot",
    title: "OncallBot",
    oneLiner: "Slack bot that routes incidents to the right on-call owner.",
    description:
      "Listens for incident keywords, looks up the current on-call rotation by service, pages the right person and opens a triage thread automatically.",
    tags: ["slack", "oncall", "incidents", "alerting", "ops"],
    ownerName: "Arjun Mehta",
    ownerSlackId: "@arjun",
    team: "Platform",
    url: "https://internal.headout.com/bots/oncall",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "slack-bot",
    title: "StandupBot",
    oneLiner: "Collects async standups and posts a team digest.",
    description:
      "DMs each team member for their async standup, then posts a tidy per-team digest with blockers highlighted, so leads skip the live meeting.",
    tags: ["slack", "standup", "async", "productivity", "team"],
    ownerName: "Priya Nair",
    ownerSlackId: "@priya",
    team: "Supply Ops",
    url: "https://internal.headout.com/bots/standup",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "slack-bot",
    title: "KudosBot",
    oneLiner: "Lets teammates give recognition that rolls up monthly.",
    description:
      "A lightweight Slack bot for peer recognition; reactions and /kudos messages roll up into a monthly leaderboard and a digest for managers.",
    tags: ["slack", "recognition", "culture", "people", "engagement"],
    ownerName: "Lena Fischer",
    ownerSlackId: "@lena",
    team: "Platform",
    url: "https://internal.headout.com/bots/kudos",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "zep",
    title: "Expense Buddy",
    oneLiner: "Zep that turns a receipt photo into a filed expense report.",
    description:
      "A Zeps agent that reads a receipt image, extracts merchant, amount and category, matches it to policy and drafts the expense report for one-click submission.",
    tags: ["expenses", "receipts", "ocr", "finance", "automation"],
    ownerName: "Maya Rao",
    ownerSlackId: "@maya",
    team: "Platform",
    url: "https://zeps-taupe.vercel.app/run/expense-buddy",
    source: "zeps-sync",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "zep",
    title: "Meeting Notes Zep",
    oneLiner: "Zep that summarizes a meeting transcript into notes and actions.",
    description:
      "Paste or forward a transcript and this Zeps agent returns a crisp summary, decisions and assigned action items with owners and due dates.",
    tags: ["meetings", "summarization", "notes", "action-items", "productivity"],
    ownerName: "Diego Alvarez",
    ownerSlackId: "@diego",
    team: "Applied AI",
    url: "https://zeps-taupe.vercel.app/run/meeting-notes",
    source: "zeps-sync",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "zep",
    title: "Supplier Email Drafter",
    oneLiner: "Zep that drafts supplier outreach from a short brief.",
    description:
      "Give it the supplier, goal and tone and this Zeps agent drafts a ready-to-send outreach or follow-up email in Headout's voice, with the key terms filled in.",
    tags: ["email", "supply", "outreach", "drafting", "communication"],
    ownerName: "Priya Nair",
    ownerSlackId: "@priya",
    team: "Supply Ops",
    url: "https://zeps-taupe.vercel.app/run/supplier-email",
    source: "zeps-sync",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "zep",
    title: "Competitor Price Watch",
    oneLiner: "Zep that checks competitor prices for an experience on demand.",
    description:
      "Ask about an experience and this Zeps agent gathers comparable competitor listings and prices, then returns a short positioning summary for pricing decisions.",
    tags: ["pricing", "competitive", "research", "monitoring", "growth"],
    ownerName: "Sara Kim",
    ownerSlackId: "@sara",
    team: "Growth",
    url: "https://zeps-taupe.vercel.app/run/competitor-price-watch",
    source: "zeps-sync",
    status: "beta",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "app",
    title: "Tour Guide Scheduler",
    oneLiner: "Assigns guides to tours based on language, rating and load.",
    description:
      "An app that matches available guides to upcoming tours by language, specialty, rating and workload, and notifies them, reducing manual scheduling for city ops.",
    tags: ["scheduling", "guides", "operations", "staffing", "logistics"],
    ownerName: "Diego Alvarez",
    ownerSlackId: "@diego",
    team: "Supply Ops",
    url: "https://internal.headout.com/guide-scheduler",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
  {
    type: "skill",
    title: "Translation QA",
    oneLiner: "Checks machine translations for tone, accuracy and length fit.",
    description:
      "A skill that reviews translated experience copy against the source for meaning, brand tone and UI length constraints, flagging segments that need a human.",
    tags: ["localization", "translation", "qa", "content", "i18n"],
    ownerName: "Tom Becker",
    ownerSlackId: "@tom",
    team: "Content",
    url: "https://internal.headout.com/skills/translation-qa",
    source: "seed",
    status: "live",
    accessLevel: "open",
    visibility: "org",
  },
];
