import type { Tool, Kit } from "@/lib/types";

export const DEMO_USER = {
  id: "alex-kim",
  name: "Alex Kim",
  slackId: "@alex.kim",
  team: "Applied AI" as const,
};

export const MOCK_OWNERS = [
  { name: "Alex Kim", slackId: "@alex.kim" },
  { name: "Jordan Lee", slackId: "@jordan.lee" },
  { name: "Maya Patel", slackId: "@maya.p" },
  { name: "Sam Rivera", slackId: "@sam.r" },
  { name: "Priya Nair", slackId: "@priya.n" },
];

export const INITIAL_APPROVED_TOOLS: Tool[] = [
  {
    id: "viator-scraper",
    name: "Viator availability scraper",
    oneLiner: "Pulls live availability from Viator partner API for supply workflows.",
    description:
      "Scheduled scraper that hits the Viator partner API and writes normalized availability snapshots to GCS. Supply Ops uses it to catch listing gaps before they hit conversion. Runs every 4 hours via Cloud Scheduler.",
    types: ["script"],
    link: "https://github.com/headout/viator-scraper",
    owner: { name: "Maya Patel", slackId: "@maya.p" },
    team: "Supply Ops",
    tags: ["scraping", "viator", "availability", "supply"],
    accessLevel: "open",
    sensitive: false,
    writeCapable: true,
    ownerInstructions: "Ping the owner on Slack — include your use case.",
    githubUrl: "https://github.com/headout/viator-scraper",
    status: "live",
    approvalStatus: "approved",
    submittedBy: "maya-patel",
    usageStats: { views: 342, clicks: 89, helpful: 24 },
    lastUpdated: "2026-06-18T10:00:00Z",
    lastUsed: "2026-06-22T14:30:00Z",
    ownerConfirmed: true,
  },
  {
    id: "bq-availability-dashboard",
    name: "BigQuery availability dashboard",
    oneLiner: "Looker dashboard for real-time inventory and availability across suppliers.",
    description:
      "Central Looker dashboard wired to BigQuery tables for inventory health, OOS rates, and supplier SLA breaches. Platform team maintains the underlying dbt models.",
    types: ["dashboard"],
    link: "https://looker.headout.internal/dashboards/availability",
    owner: { name: "Jordan Lee", slackId: "@jordan.lee" },
    team: "Platform",
    tags: ["bigquery", "looker", "inventory", "analytics"],
    accessLevel: "request",
    sensitive: true,
    writeCapable: false,
    ownerInstructions: "Request Looker access in #data-platform. Mention inventory dashboards — Jordan provisions read-only seats within 2 days.",
    accessContact: "@jordan.lee in #data-platform",
    status: "live",
    approvalStatus: "approved",
    submittedBy: "jordan-lee",
    usageStats: { views: 518, clicks: 201, helpful: 41 },
    lastUpdated: "2026-06-10T09:00:00Z",
    lastUsed: "2026-06-21T11:00:00Z",
    ownerConfirmed: true,
  },
  {
    id: "claude-cf-audit",
    name: "Claude CF-audit skill",
    oneLiner: "Audits Cloudflare configs against Headout security baselines.",
    description:
      "Claude Code skill that reads CF zone exports and flags misconfigured WAF rules, TLS settings, and cache policies. Outputs a markdown report with severity tags.",
    types: ["skill"],
    link: "https://github.com/headout/skills/tree/main/cf-audit",
    owner: { name: "Alex Kim", slackId: "@alex.kim" },
    team: "Applied AI",
    tags: ["claude", "cloudflare", "security", "audit"],
    accessLevel: "open",
    sensitive: false,
    writeCapable: false,
    ownerInstructions: "Ping the owner on Slack — include your use case.",
    githubUrl: "https://github.com/headout/skills/tree/main/cf-audit",
    status: "live",
    approvalStatus: "approved",
    submittedBy: "alex-kim",
    usageStats: { views: 156, clicks: 67, helpful: 18 },
    lastUpdated: "2026-05-28T16:00:00Z",
    lastUsed: "2026-06-19T08:45:00Z",
    ownerConfirmed: true,
  },
  {
    id: "slack-qa-bot",
    name: "Slack content QA bot",
    oneLiner: "Flags grammar, tone, and brand-voice issues in content drafts.",
    description:
      "Slack bot that listens in #content-review. Paste a draft or link a Google Doc — it returns inline suggestions aligned to Headout voice guidelines.",
    types: ["slack-bot", "app"],
    link: "https://slack.com/app_redirect?app=content-qa-bot",
    owner: { name: "Sofia Reyes", slackId: "@sofia.r" },
    team: "Content",
    tags: ["slack", "qa", "content", "brand-voice"],
    accessLevel: "open",
    sensitive: false,
    writeCapable: false,
    ownerInstructions: "Ping the owner on Slack — include your use case.",
    status: "live",
    approvalStatus: "approved",
    submittedBy: "sofia-reyes",
    usageStats: { views: 289, clicks: 134, helpful: 52 },
    lastUpdated: "2026-06-05T11:00:00Z",
    lastUsed: "2026-06-21T15:00:00Z",
    ownerConfirmed: true,
  },
  {
    id: "pricing-audit-mcp",
    name: "Pricing audit MCP",
    oneLiner: "MCP server that compares Headout prices against OTAs in real time.",
    description:
      "Model Context Protocol server exposing search_pricing_gaps and get_competitor_rates tools. Growth analysts plug it into Claude Code for ad-hoc pricing investigations.",
    types: ["mcp", "skill"],
    link: "https://github.com/headout/mcp-pricing-audit",
    owner: { name: "Tom Walsh", slackId: "@tom.w" },
    team: "Growth",
    tags: ["mcp", "pricing", "competitive", "claude"],
    accessLevel: "request",
    sensitive: false,
    writeCapable: false,
    ownerInstructions: "Add the MCP config to Claude Code, then DM @tom.w for API credentials. Read-only pricing data only.",
    accessContact: "@tom.w in #growth-tools",
    githubUrl: "https://github.com/headout/mcp-pricing-audit",
    status: "live",
    approvalStatus: "approved",
    submittedBy: "tom-walsh",
    usageStats: { views: 198, clicks: 72, helpful: 31 },
    lastUpdated: "2026-06-15T12:00:00Z",
    lastUsed: "2026-06-20T16:20:00Z",
    ownerConfirmed: true,
  },
  {
    id: "ad-copy-qa",
    name: "Content ad-copy QA tool",
    oneLiner: "Web app that scores ad copy against Headout performance playbooks.",
    description:
      "Paste ad copy and get a scorecard: headline strength, CTA clarity, character limits per channel, and A/B test suggestions. Built on Replit, wired to our brand guidelines doc.",
    types: ["app"],
    link: "https://adcopy-qa.headout.tools",
    owner: { name: "Alex Kim", slackId: "@alex.kim" },
    team: "Content",
    tags: ["ads", "copy", "qa", "growth"],
    accessLevel: "open",
    sensitive: false,
    writeCapable: false,
    ownerInstructions: "Ping the owner on Slack — include your use case.",
    status: "live",
    approvalStatus: "approved",
    submittedBy: "alex-kim",
    usageStats: { views: 412, clicks: 178, helpful: 63 },
    lastUpdated: "2026-06-01T14:00:00Z",
    lastUsed: "2026-06-22T10:15:00Z",
    ownerConfirmed: true,
  },
  {
    id: "guardian-auth-plugin",
    name: "Guardian auth plugin",
    oneLiner: "Drop-in Guardian SSO for internal Replit and Vercel apps.",
    description:
      "Next.js middleware plugin that handles Google Workspace SSO via Guardian. One import gives you session management and role checks for internal tools.",
    types: ["plugin"],
    link: "https://github.com/headout/guardian-auth-plugin",
    owner: { name: "Jordan Lee", slackId: "@jordan.lee" },
    team: "Platform",
    tags: ["auth", "guardian", "sso", "plugin"],
    accessLevel: "open",
    sensitive: false,
    writeCapable: false,
    ownerInstructions: "Ping the owner on Slack — include your use case.",
    githubUrl: "https://github.com/headout/guardian-auth-plugin",
    status: "live",
    approvalStatus: "approved",
    submittedBy: "jordan-lee",
    usageStats: { views: 267, clicks: 95, helpful: 29 },
    lastUpdated: "2026-04-20T11:00:00Z",
    lastUsed: "2026-06-17T13:00:00Z",
    ownerConfirmed: true,
  },
  {
    id: "competitor-price-monitor",
    name: "Competitor price monitor",
    oneLiner: "Daily scraper that tracks OTA pricing for top 500 SKUs.",
    description:
      "Python script on a cron that scrapes GetYourGuide, Viator, and Klook listing pages. Diffs land in BigQuery; alerts fire in #growth-pricing when gaps exceed 8%.",
    types: ["script"],
    link: "https://github.com/headout/competitor-price-monitor",
    owner: { name: "Tom Walsh", slackId: "@tom.w" },
    team: "Growth",
    tags: ["scraping", "pricing", "competitive"],
    accessLevel: "open",
    sensitive: false,
    writeCapable: false,
    ownerInstructions: "Ping the owner on Slack — include your use case.",
    githubUrl: "https://github.com/headout/competitor-price-monitor",
    status: "live",
    approvalStatus: "approved",
    submittedBy: "tom-walsh",
    usageStats: { views: 231, clicks: 58, helpful: 15 },
    lastUpdated: "2026-06-08T08:00:00Z",
    lastUsed: "2026-06-21T07:30:00Z",
    ownerConfirmed: true,
  },
  {
    id: "seo-meta-skill",
    name: "SEO meta generator skill",
    oneLiner: "Claude skill that drafts SEO titles and meta descriptions at scale.",
    description:
      "Feed it a product ID or URL slug — it pulls live PDP data and drafts title tags, meta descriptions, and OG copy following Headout SEO templates.",
    types: ["skill"],
    link: "",
    owner: { name: "Alex Kim", slackId: "@alex.kim" },
    team: "Growth",
    tags: ["seo", "claude", "content", "metadata"],
    accessLevel: "open",
    sensitive: false,
    writeCapable: false,
    ownerInstructions: "Ping the owner on Slack — include your use case.",
    githubUrl: "https://github.com/headout/skills/tree/main/seo-meta",
    status: "planned",
    approvalStatus: "approved",
    submittedBy: "alex-kim",
    usageStats: { views: 174, clicks: 81, helpful: 22 },
    lastUpdated: "2026-06-20T09:00:00Z",
    lastUsed: "2026-06-20T09:00:00Z",
    ownerConfirmed: true,
  },
  {
    id: "inventory-sync-dashboard",
    name: "Inventory sync dashboard",
    oneLiner: "Tracks supplier feed sync latency and error rates across integrations.",
    description:
      "Grafana dashboard showing last-sync timestamps, error counts, and retry queues for every supplier integration. Red rows mean a feed is stale.",
    types: ["dashboard"],
    link: "https://grafana.headout.internal/d/inventory-sync",
    owner: { name: "Maya Patel", slackId: "@maya.p" },
    team: "Supply Ops",
    tags: ["inventory", "suppliers", "monitoring"],
    accessLevel: "request",
    sensitive: false,
    writeCapable: false,
    ownerInstructions: "Ping the owner on Slack — include your use case.",
    accessContact: "@maya.p in #supply-ops",
    status: "live",
    approvalStatus: "approved",
    submittedBy: "maya-patel",
    usageStats: { views: 445, clicks: 167, helpful: 38 },
    lastUpdated: "2026-06-12T15:00:00Z",
    lastUsed: "2026-06-22T06:00:00Z",
    ownerConfirmed: true,
  },
  {
    id: "booking-debug-mcp",
    name: "Booking debug MCP",
    oneLiner: "MCP tools for tracing booking failures end-to-end in staging.",
    description:
      "Exposes get_booking_trace, search_payment_errors, and replay_webhook MCP tools. Platform engineers use it in Claude Code to debug Zapdos checkout issues.",
    types: ["mcp"],
    link: "https://github.com/headout/mcp-booking-debug",
    owner: { name: "Jordan Lee", slackId: "@jordan.lee" },
    team: "Platform",
    tags: ["mcp", "booking", "debug", "zapdos"],
    accessLevel: "sensitive",
    sensitive: true,
    writeCapable: false,
    ownerInstructions: "Ping the owner on Slack — include your use case.",
    accessContact: "@jordan.lee in #platform-eng",
    githubUrl: "https://github.com/headout/mcp-booking-debug",
    status: "beta",
    approvalStatus: "approved",
    submittedBy: "jordan-lee",
    usageStats: { views: 133, clicks: 49, helpful: 17 },
    lastUpdated: "2026-06-19T18:00:00Z",
    lastUsed: "2026-06-18T12:00:00Z",
    ownerConfirmed: true,
  },
  {
    id: "zendesk-triage-bot",
    name: "Zendesk triage bot",
    oneLiner: "Auto-classifies and routes support tickets using Headout taxonomies.",
    description:
      "Slack-integrated bot that reads incoming Zendesk tickets, suggests priority and assignee, and drafts first-response templates. Applied AI team maintains the classifier.",
    types: ["slack-bot"],
    link: "https://slack.com/app_redirect?app=zendesk-triage",
    owner: { name: "Priya Sharma", slackId: "@priya.s" },
    team: "Applied AI",
    tags: ["slack", "zendesk", "support", "triage"],
    accessLevel: "open",
    sensitive: false,
    writeCapable: false,
    ownerInstructions: "Ping the owner on Slack — include your use case.",
    status: "deprecated",
    approvalStatus: "approved",
    submittedBy: "priya-sharma",
    usageStats: { views: 201, clicks: 88, helpful: 27 },
    lastUpdated: "2025-10-01T10:00:00Z",
    linkUnreachable: true,
    lastUsed: "2026-01-15T09:00:00Z",
    ownerConfirmed: true,
  },
  {
    id: "pdp-image-optimiser",
    name: "PDP image optimiser",
    oneLiner: "Plugin that compresses and crops product images to Headout specs.",
    description:
      "Figma and CMS plugin that batch-processes product images: correct aspect ratio, WebP conversion, alt-text suggestions. Content team runs it before every city launch.",
    types: ["plugin"],
    link: "",
    owner: { name: "Alex Kim", slackId: "@alex.kim" },
    team: "Content",
    tags: ["images", "cms", "figma", "pdp"],
    accessLevel: "open",
    sensitive: false,
    writeCapable: false,
    ownerInstructions: "Ping the owner on Slack — include your use case.",
    githubUrl: "https://github.com/headout/pdp-image-optimiser",
    status: "planned",
    approvalStatus: "approved",
    submittedBy: "sofia-reyes",
    usageStats: { views: 118, clicks: 44, helpful: 11 },
    lastUpdated: "2026-06-14T10:00:00Z",
    lastUsed: "2026-03-01T10:00:00Z",
    ownerConfirmed: false,
  },
  {
    id: "tour-editor-replit",
    name: "Tour editor Replit app",
    oneLiner: "Lightweight editor for supply ops to update tour copy and inclusions.",
    description:
      "Replit-hosted internal app with a form-based UI for updating tour descriptions, inclusions, and meeting points. Writes directly to the supply CMS API.",
    types: ["app"],
    link: "https://tour-editor.headout.tools",
    owner: { name: "Maya Patel", slackId: "@maya.p" },
    team: "Supply Ops",
    tags: ["replit", "tours", "cms", "supply"],
    accessLevel: "request",
    sensitive: false,
    writeCapable: true,
    ownerInstructions: "Ping the owner on Slack — include your use case.",
    accessContact: "@maya.p in #supply-ops",
    status: "live",
    approvalStatus: "approved",
    submittedBy: "maya-patel",
    usageStats: { views: 276, clicks: 112, helpful: 33 },
    lastUpdated: "2026-05-05T13:00:00Z",
    linkUnreachable: true,
    lastUsed: "2026-06-15T09:30:00Z",
    ownerConfirmed: true,
  },
];

export const KITS: Kit[] = [
  {
    id: "essentials",
    name: "Essentials",
    description: "Cross-team staples everyone reaches for — auth, QA, dashboards, and support.",
    toolIds: [
      "guardian-auth-plugin",
      "slack-qa-bot",
      "zendesk-triage-bot",
      "claude-cf-audit",
      "bq-availability-dashboard",
      "ad-copy-qa",
    ],
    accentVar: "--color-dreamypale-400",
  },
  {
    id: "supply-ops",
    name: "Supply Ops",
    description: "Scrapers, inventory sync, and tour editing for the supply team.",
    toolIds: [
      "viator-scraper",
      "inventory-sync-dashboard",
      "tour-editor-replit",
    ],
    accentVar: "--color-peachyorange-300",
  },
  {
    id: "growth",
    name: "Growth",
    description: "Pricing, competitive intel, and SEO tooling for growth analysts.",
    toolIds: [
      "pricing-audit-mcp",
      "competitor-price-monitor",
      "seo-meta-skill",
    ],
    accentVar: "--color-joymustard-300",
  },
  {
    id: "content",
    name: "Content",
    description: "Copy QA, ad scoring, and image tooling for the content team.",
    toolIds: [
      "slack-qa-bot",
      "ad-copy-qa",
      "pdp-image-optimiser",
    ],
    accentVar: "--color-candy-200",
  },
  {
    id: "applied-ai-platform",
    name: "Applied AI / Platform",
    description: "Skills, MCPs, auth, and infra debug tools for builders.",
    toolIds: [
      "claude-cf-audit",
      "booking-debug-mcp",
      "zendesk-triage-bot",
      "guardian-auth-plugin",
      "bq-availability-dashboard",
    ],
    accentVar: "--color-oceanblue-200",
  },
];

export function getKitById(id: string): Kit | undefined {
  return KITS.find((kit) => kit.id === id);
}

export function getKitToolCount(kit: Kit, tools: Tool[]): number {
  const approvedIds = new Set(
    tools.filter((t) => t.approvalStatus === "approved").map((t) => t.id),
  );
  return kit.toolIds.filter((id) => approvedIds.has(id)).length;
}

export function getToolsForKit(kit: Kit, tools: Tool[]): Tool[] {
  const idSet = new Set(kit.toolIds);
  return tools.filter((t) => t.approvalStatus === "approved" && idSet.has(t.id));
}

export const INITIAL_PENDING_TOOLS: Tool[] = [
  {
    id: "unified-llm-router-idea",
    name: "Unified LLM router",
    oneLiner: "Single internal endpoint to route prompts across approved models with spend caps.",
    description:
      "Proposed shared router for internal apps — rate limits, model allowlists, and audit logging. Not built yet.",
    types: ["app", "mcp"],
    link: "",
    owner: { name: "Priya Sharma", slackId: "@priya.s" },
    team: "Applied AI",
    tags: ["llm", "routing", "platform"],
    accessLevel: "open",
    sensitive: false,
    writeCapable: false,
    ownerInstructions: "Still an idea — comment in #applied-ai if you want to co-build.",
    status: "planned",
    approvalStatus: "pending",
    submittedBy: "priya-sharma",
    usageStats: { views: 0, clicks: 0, helpful: 0 },
    lastUpdated: "2026-06-22T10:00:00Z",
    lastUsed: "2026-06-22T10:00:00Z",
    ownerConfirmed: true,
  },

  {
    id: "gttd-feed-validator",
    name: "GTTD feed validator",
    oneLiner: "Validates Google Things to Do feed XML before submission.",
    description:
      "CLI script that lints GTTD feed files against Google's schema and Headout-specific rules. Catches missing geo coordinates and invalid price formats.",
    types: ["script"],
    link: "https://github.com/headout/gttd-validator",
    owner: { name: "Maya Patel", slackId: "@maya.p" },
    team: "Supply Ops",
    tags: ["gttd", "google", "feed", "validation"],
    accessLevel: "open",
    sensitive: false,
    writeCapable: false,
    ownerInstructions: "Ping the owner on Slack — include your use case.",
    githubUrl: "https://github.com/headout/gttd-validator",
    status: "live",
    approvalStatus: "pending",
    submittedBy: "maya-patel",
    usageStats: { views: 0, clicks: 0, helpful: 0 },
    lastUpdated: "2026-06-22T10:00:00Z",
    lastUsed: "2026-06-22T10:00:00Z",
    ownerConfirmed: true,
  },
  {
    id: "agent-memory-plugin",
    name: "Agent memory plugin",
    oneLiner: "Persists Claude agent context across sessions for internal tools.",
    description:
      "Plugin that stores conversation summaries and tool outputs in a lightweight KV store. Lets multi-step agent workflows resume where they left off.",
    types: ["plugin", "mcp"],
    link: "https://github.com/headout/agent-memory",
    owner: { name: "Priya Sharma", slackId: "@priya.s" },
    team: "Applied AI",
    tags: ["claude", "agents", "memory", "plugin"],
    accessLevel: "request",
    sensitive: true,
    writeCapable: false,
    ownerInstructions: "Ping the owner on Slack — include your use case.",
    accessContact: "@priya.s in #applied-ai",
    githubUrl: "https://github.com/headout/agent-memory",
    status: "live",
    approvalStatus: "pending",
    submittedBy: "priya-sharma",
    usageStats: { views: 0, clicks: 0, helpful: 0 },
    lastUpdated: "2026-06-21T14:00:00Z",
    lastUsed: "2026-06-21T14:00:00Z",
    ownerConfirmed: true,
  },
  {
    id: "conversion-funnel-dashboard",
    name: "Conversion funnel dashboard",
    oneLiner: "Tracks PDP → select → checkout → confirm drop-off by city.",
    description:
      "Looker dashboard built on Segment events. Growth team uses it weekly to spot funnel regressions after releases.",
    types: ["dashboard"],
    link: "https://looker.headout.internal/dashboards/conversion-funnel",
    owner: { name: "Tom Walsh", slackId: "@tom.w" },
    team: "Growth",
    tags: ["conversion", "funnel", "analytics", "growth"],
    accessLevel: "request",
    sensitive: false,
    writeCapable: false,
    ownerInstructions: "Ping the owner on Slack — include your use case.",
    accessContact: "@tom.w in #growth-analytics",
    status: "live",
    approvalStatus: "pending",
    submittedBy: "tom-walsh",
    usageStats: { views: 0, clicks: 0, helpful: 0 },
    lastUpdated: "2026-06-20T16:00:00Z",
    lastUsed: "2026-06-20T16:00:00Z",
    ownerConfirmed: true,
  },
];

export const MOCK_README_PREVIEW = `# Tool README

## Overview
Auto-pulled from GitHub. This is a mocked preview for the demo.

## Setup
\`\`\`bash
npm install
npm run dev
\`\`\`

## Usage
Describe your tool here. The real v1 will parse your actual README.`;

export function findDedupMatches(
  name: string,
  oneLiner: string,
  tools: Tool[],
): Tool[] {
  const query = `${name} ${oneLiner}`.toLowerCase().trim();
  if (query.length < 3) return [];

  const keywords = query.split(/\s+/).filter((w) => w.length > 2);
  if (keywords.length === 0) return [];

  const scored = tools
    .map((tool) => {
      const haystack =
        `${tool.name} ${tool.oneLiner} ${tool.tags.join(" ")} ${tool.types.join(" ")}`.toLowerCase();
      const score = keywords.filter((k) => haystack.includes(k)).length;
      return { tool, score };
    })
    .filter(({ score }) => score >= 2)
    .sort((a, b) => b.score - a.score);

  return scored.slice(0, 2).map(({ tool }) => tool);
}
